// <auto-generated />
using System;
using HRISAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HRISAPI.Migrations
{
    [DbContext(typeof(HRISDbContext))]
    [Migration("20220705084505_Edits")]
    partial class Edits
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("HRISAPI.Models.FM.BloodType", b =>
                {
                    b.Property<int>("BloodTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BloodTypeID"), 1L, 1);

                    b.Property<DateTime>("DateTimeStamp")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsDel")
                        .HasColumnType("bit");

                    b.Property<string>("UserStamp")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("BloodTypeID");

                    b.ToTable("BloodType", "FM");
                });

            modelBuilder.Entity("HRISAPI.Models.FM.CivilStatus", b =>
                {
                    b.Property<int>("CivilStatusID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CivilStatusID"), 1L, 1);

                    b.Property<DateTime>("DateTimeStamp")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsDel")
                        .HasColumnType("bit");

                    b.Property<string>("UserStamp")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("CivilStatusID");

                    b.ToTable("CivilStatus", "FM");
                });

            modelBuilder.Entity("HRISAPI.Models.PDS.Person", b =>
                {
                    b.Property<int>("PersonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonID"), 1L, 1);

                    b.Property<int>("BloodTypeID")
                        .HasColumnType("int");

                    b.Property<int>("CivilStatusID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateTimeStamp")
                        .HasColumnType("datetime");

                    b.Property<string>("ExtensionName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsDel")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("UserStamp")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("PersonID");

                    b.HasIndex("BloodTypeID");

                    b.HasIndex("CivilStatusID");

                    b.ToTable("Person", "PDS");
                });

            modelBuilder.Entity("HRISAPI.Models.PDS.Person", b =>
                {
                    b.HasOne("HRISAPI.Models.FM.BloodType", "BloodType")
                        .WithMany("Persons")
                        .HasForeignKey("BloodTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRISAPI.Models.FM.CivilStatus", "CivilStatus")
                        .WithMany("Persons")
                        .HasForeignKey("CivilStatusID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BloodType");

                    b.Navigation("CivilStatus");
                });

            modelBuilder.Entity("HRISAPI.Models.FM.BloodType", b =>
                {
                    b.Navigation("Persons");
                });

            modelBuilder.Entity("HRISAPI.Models.FM.CivilStatus", b =>
                {
                    b.Navigation("Persons");
                });
#pragma warning restore 612, 618
        }
    }
}
